baseUrl: 'http://www.itsairborne.com/'
theme: 'PaperMod'
googleAnalytics: G-R2WREQMZ3M
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: protect
      name: Protecting Yourself
      url: /categories/protecting-yourself/
      weight: 2
    - identifier: engineer
      name: Engineering Methods
      url: /categories/engineering-methods/
      weight: 3
    - identifier: ventilation
      name: Ventilation, Air Quality and CO2
      url: /categories/ventilation-air-quality-and-co2/
      weight: 4
cascade:
  ShowReadingTime: true
  ShowPostNavLinks: true
  author: "Joey Fox, P. Eng, M.A.Sc"