baseUrl: 'http://www.itsairborne.com/'
title: "It's Airborne."
theme: 'PaperMod'
googleAnalytics: G-R2WREQMZ3M
enableRobotsTXT: true
outputs:
  home:
    - html
    - rss
    - json
menu:
  main:
    - identifier: protect
      name: Protecting Yourself
      url: /categories/protecting-yourself/
      weight: 2
    - identifier: engineer
      name: Engineering Methods
      url: /categories/engineering-methods/
      weight: 3
    - identifier: ventilation
      name: Ventilation, Air Quality and CO2
      url: /categories/ventilation-air-quality-and-co2/
      weight: 4
    - identifier: search
      name: ...
      url: /search/
      weight: 5
cascade:
  ShowReadingTime: true
  ShowPostNavLinks: true
  author: "Joey Fox, P. Eng, M.A.Sc"
params:
  description: "#COVIDisAirborne. If you know how it spreads, you know how to stop it."
  ShowShareButtons: true
  defaultTheme: dark
  homeInfoParams:
    title: "#COVIDisAirborne."
    content: "If you know how it spreads, you know how to stop it. Posts by [@joeyfox85](https://twitter.com/joeyfox85)"
  socialIcons: # optional
    - name: "twitter"
      url: "https://twitter.com/joeyfox85/status/1554939526560333825"
    - name: "github"
      url: "https://github.com/jsherman256/covid-air/"